spring:
  datasource:
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    driver-class-name: ${DATASOURCE_DRIVERNAME}
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: ${DATASOURCE_DIALECT}
        format-sql: true
      show-sql: true

#logging:
#  level:
#    root: DEBUG
