spring:
  datasource:
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
      show-sql: true

#logging:
#  level:
#    root: DEBUG
